version: '3.7'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    privileged: true # Guvenlik Riski Icerebilir!
    restart: always
    container_name: jenkins
    user: root
    ports:
      - 7777:8080
      - 5000:5000
    volumes:
      - './jenkins_configuration:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
