version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'localhost'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8080:80'
      - '8443:443'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
  jenkins:
    image: 'jenkins/jenkins:lts'
    privileged: true
    restart: always
    container_name: jenkins
    user: root
    ports:
      - 7777:8080
      - 5000:5000
    volumes:
      - './jenkins_configuration:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'